/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpendIntelligenceRouteImport } from './routes/spend-intelligence'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ReducaoDeCustosRouteImport } from './routes/reducao-de-custos'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as CostOptimizationRouteImport } from './routes/cost-optimization'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BpoDeComprasRouteImport } from './routes/bpo-de-compras'
import { Route as IndexRouteImport } from './routes/index'

const SpendIntelligenceRoute = SpendIntelligenceRouteImport.update({
  id: '/spend-intelligence',
  path: '/spend-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReducaoDeCustosRoute = ReducaoDeCustosRouteImport.update({
  id: '/reducao-de-custos',
  path: '/reducao-de-custos',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const CostOptimizationRoute = CostOptimizationRouteImport.update({
  id: '/cost-optimization',
  path: '/cost-optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BpoDeComprasRoute = BpoDeComprasRouteImport.update({
  id: '/bpo-de-compras',
  path: '/bpo-de-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bpo-de-compras': typeof BpoDeComprasRoute
  '/contato': typeof ContatoRoute
  '/cost-optimization': typeof CostOptimizationRoute
  '/cursos': typeof CursosRoute
  '/reducao-de-custos': typeof ReducaoDeCustosRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/spend-intelligence': typeof SpendIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bpo-de-compras': typeof BpoDeComprasRoute
  '/contato': typeof ContatoRoute
  '/cost-optimization': typeof CostOptimizationRoute
  '/cursos': typeof CursosRoute
  '/reducao-de-custos': typeof ReducaoDeCustosRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/spend-intelligence': typeof SpendIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bpo-de-compras': typeof BpoDeComprasRoute
  '/contato': typeof ContatoRoute
  '/cost-optimization': typeof CostOptimizationRoute
  '/cursos': typeof CursosRoute
  '/reducao-de-custos': typeof ReducaoDeCustosRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/spend-intelligence': typeof SpendIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bpo-de-compras'
    | '/contato'
    | '/cost-optimization'
    | '/cursos'
    | '/reducao-de-custos'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/spend-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bpo-de-compras'
    | '/contato'
    | '/cost-optimization'
    | '/cursos'
    | '/reducao-de-custos'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/spend-intelligence'
  id:
    | '__root__'
    | '/'
    | '/bpo-de-compras'
    | '/contato'
    | '/cost-optimization'
    | '/cursos'
    | '/reducao-de-custos'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/spend-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BpoDeComprasRoute: typeof BpoDeComprasRoute
  ContatoRoute: typeof ContatoRoute
  CostOptimizationRoute: typeof CostOptimizationRoute
  CursosRoute: typeof CursosRoute
  ReducaoDeCustosRoute: typeof ReducaoDeCustosRoute
  ServicosRoute: typeof ServicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  SpendIntelligenceRoute: typeof SpendIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spend-intelligence': {
      id: '/spend-intelligence'
      path: '/spend-intelligence'
      fullPath: '/spend-intelligence'
      preLoaderRoute: typeof SpendIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reducao-de-custos': {
      id: '/reducao-de-custos'
      path: '/reducao-de-custos'
      fullPath: '/reducao-de-custos'
      preLoaderRoute: typeof ReducaoDeCustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-optimization': {
      id: '/cost-optimization'
      path: '/cost-optimization'
      fullPath: '/cost-optimization'
      preLoaderRoute: typeof CostOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bpo-de-compras': {
      id: '/bpo-de-compras'
      path: '/bpo-de-compras'
      fullPath: '/bpo-de-compras'
      preLoaderRoute: typeof BpoDeComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BpoDeComprasRoute: BpoDeComprasRoute,
  ContatoRoute: ContatoRoute,
  CostOptimizationRoute: CostOptimizationRoute,
  CursosRoute: CursosRoute,
  ReducaoDeCustosRoute: ReducaoDeCustosRoute,
  ServicosRoute: ServicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  SpendIntelligenceRoute: SpendIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
