/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RevisaoPreFechamentoRouteImport } from './routes/revisao-pre-fechamento'
import { Route as ReducaoDeCustosRouteImport } from './routes/reducao-de-custos'
import { Route as OtimizacaoDeCustosRouteImport } from './routes/otimizacao-de-custos'
import { Route as MaturidadeEmComprasRouteImport } from './routes/maturidade-em-compras'
import { Route as InteligenciaDeGastosRouteImport } from './routes/inteligencia-de-gastos'
import { Route as GestaoDeFornecedoresRouteImport } from './routes/gestao-de-fornecedores'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BpoDeComprasRouteImport } from './routes/bpo-de-compras'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoPreFechamentoRoute = RevisaoPreFechamentoRouteImport.update({
  id: '/revisao-pre-fechamento',
  path: '/revisao-pre-fechamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ReducaoDeCustosRoute = ReducaoDeCustosRouteImport.update({
  id: '/reducao-de-custos',
  path: '/reducao-de-custos',
  getParentRoute: () => rootRouteImport,
} as any)
const OtimizacaoDeCustosRoute = OtimizacaoDeCustosRouteImport.update({
  id: '/otimizacao-de-custos',
  path: '/otimizacao-de-custos',
  getParentRoute: () => rootRouteImport,
} as any)
const MaturidadeEmComprasRoute = MaturidadeEmComprasRouteImport.update({
  id: '/maturidade-em-compras',
  path: '/maturidade-em-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaDeGastosRoute = InteligenciaDeGastosRouteImport.update({
  id: '/inteligencia-de-gastos',
  path: '/inteligencia-de-gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoDeFornecedoresRoute = GestaoDeFornecedoresRouteImport.update({
  id: '/gestao-de-fornecedores',
  path: '/gestao-de-fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BpoDeComprasRoute = BpoDeComprasRouteImport.update({
  id: '/bpo-de-compras',
  path: '/bpo-de-compras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bpo-de-compras': typeof BpoDeComprasRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/gestao-de-fornecedores': typeof GestaoDeFornecedoresRoute
  '/inteligencia-de-gastos': typeof InteligenciaDeGastosRoute
  '/maturidade-em-compras': typeof MaturidadeEmComprasRoute
  '/otimizacao-de-custos': typeof OtimizacaoDeCustosRoute
  '/reducao-de-custos': typeof ReducaoDeCustosRoute
  '/revisao-pre-fechamento': typeof RevisaoPreFechamentoRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bpo-de-compras': typeof BpoDeComprasRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/gestao-de-fornecedores': typeof GestaoDeFornecedoresRoute
  '/inteligencia-de-gastos': typeof InteligenciaDeGastosRoute
  '/maturidade-em-compras': typeof MaturidadeEmComprasRoute
  '/otimizacao-de-custos': typeof OtimizacaoDeCustosRoute
  '/reducao-de-custos': typeof ReducaoDeCustosRoute
  '/revisao-pre-fechamento': typeof RevisaoPreFechamentoRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bpo-de-compras': typeof BpoDeComprasRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/gestao-de-fornecedores': typeof GestaoDeFornecedoresRoute
  '/inteligencia-de-gastos': typeof InteligenciaDeGastosRoute
  '/maturidade-em-compras': typeof MaturidadeEmComprasRoute
  '/otimizacao-de-custos': typeof OtimizacaoDeCustosRoute
  '/reducao-de-custos': typeof ReducaoDeCustosRoute
  '/revisao-pre-fechamento': typeof RevisaoPreFechamentoRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bpo-de-compras'
    | '/contato'
    | '/cursos'
    | '/gestao-de-fornecedores'
    | '/inteligencia-de-gastos'
    | '/maturidade-em-compras'
    | '/otimizacao-de-custos'
    | '/reducao-de-custos'
    | '/revisao-pre-fechamento'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bpo-de-compras'
    | '/contato'
    | '/cursos'
    | '/gestao-de-fornecedores'
    | '/inteligencia-de-gastos'
    | '/maturidade-em-compras'
    | '/otimizacao-de-custos'
    | '/reducao-de-custos'
    | '/revisao-pre-fechamento'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/bpo-de-compras'
    | '/contato'
    | '/cursos'
    | '/gestao-de-fornecedores'
    | '/inteligencia-de-gastos'
    | '/maturidade-em-compras'
    | '/otimizacao-de-custos'
    | '/reducao-de-custos'
    | '/revisao-pre-fechamento'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BpoDeComprasRoute: typeof BpoDeComprasRoute
  ContatoRoute: typeof ContatoRoute
  CursosRoute: typeof CursosRoute
  GestaoDeFornecedoresRoute: typeof GestaoDeFornecedoresRoute
  InteligenciaDeGastosRoute: typeof InteligenciaDeGastosRoute
  MaturidadeEmComprasRoute: typeof MaturidadeEmComprasRoute
  OtimizacaoDeCustosRoute: typeof OtimizacaoDeCustosRoute
  ReducaoDeCustosRoute: typeof ReducaoDeCustosRoute
  RevisaoPreFechamentoRoute: typeof RevisaoPreFechamentoRoute
  ServicosRoute: typeof ServicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao-pre-fechamento': {
      id: '/revisao-pre-fechamento'
      path: '/revisao-pre-fechamento'
      fullPath: '/revisao-pre-fechamento'
      preLoaderRoute: typeof RevisaoPreFechamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reducao-de-custos': {
      id: '/reducao-de-custos'
      path: '/reducao-de-custos'
      fullPath: '/reducao-de-custos'
      preLoaderRoute: typeof ReducaoDeCustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otimizacao-de-custos': {
      id: '/otimizacao-de-custos'
      path: '/otimizacao-de-custos'
      fullPath: '/otimizacao-de-custos'
      preLoaderRoute: typeof OtimizacaoDeCustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maturidade-em-compras': {
      id: '/maturidade-em-compras'
      path: '/maturidade-em-compras'
      fullPath: '/maturidade-em-compras'
      preLoaderRoute: typeof MaturidadeEmComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia-de-gastos': {
      id: '/inteligencia-de-gastos'
      path: '/inteligencia-de-gastos'
      fullPath: '/inteligencia-de-gastos'
      preLoaderRoute: typeof InteligenciaDeGastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-de-fornecedores': {
      id: '/gestao-de-fornecedores'
      path: '/gestao-de-fornecedores'
      fullPath: '/gestao-de-fornecedores'
      preLoaderRoute: typeof GestaoDeFornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bpo-de-compras': {
      id: '/bpo-de-compras'
      path: '/bpo-de-compras'
      fullPath: '/bpo-de-compras'
      preLoaderRoute: typeof BpoDeComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BpoDeComprasRoute: BpoDeComprasRoute,
  ContatoRoute: ContatoRoute,
  CursosRoute: CursosRoute,
  GestaoDeFornecedoresRoute: GestaoDeFornecedoresRoute,
  InteligenciaDeGastosRoute: InteligenciaDeGastosRoute,
  MaturidadeEmComprasRoute: MaturidadeEmComprasRoute,
  OtimizacaoDeCustosRoute: OtimizacaoDeCustosRoute,
  ReducaoDeCustosRoute: ReducaoDeCustosRoute,
  RevisaoPreFechamentoRoute: RevisaoPreFechamentoRoute,
  ServicosRoute: ServicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
